name: Android 12 GKI Kernel Builder
on:
  workflow_dispatch:
    inputs:
      KERNEL_SUFFIX:
        description: '内核名称修改(可改中文和emoji)'
        required: true
        default: '-酷安FutabaWa'
      KERNEL_TIME:
        description: "内核构建日期更改(默认为原厂)"
        required: true
        default: 'Tue Dec 17 23:36:49 UTC 2024'
      enable_feature_x:
        description: "是否启用kpm"
        required: false
        default: false
        type: boolean
      enable_feature_y:
        description: "是否启用lz4kd"
        required: false
        default: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # --- 最大化构建空间：建议保留此步骤以防空间不足 ---
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 2048
          temp-reserve-mb: 512
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-swap: 'true'
          remove-tool-cache: 'true'
          remove-packages: 'true'

      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Install dependencies
        run: |
          sudo apt update && sudo apt upgrade -y
          sudo apt install -y python3 git curl ccache build-essential flex bison libssl-dev libelf-dev bc wget tar # 确保安装了 wget 和 tar
          sudo apt autoremove -y && sudo apt clean
          
      - name: Clone Common Kernel (5.10)
        run: |
          mkdir kernel_workspace
          cd kernel_workspace
          git clone https://github.com/tan666000/android_gki_kernel_5.10_common.git -b android12-5.10-2025-06 kernel_platform
          cd kernel_platform
          git checkout android12-5.10-2025-06
          
      - name: Set up SukiSU for 5.10
        run: |
          cd kernel_workspace/kernel_platform
          curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -s main
          
      - name: Set up susfs for 5.10
        run: |
          cd kernel_workspace
          git clone https://gitlab.com/simonpunk/susfs4ksu.git -b gki-android12-5.10
          cd kernel_platform
          cp ../susfs4ksu/kernel_patches/50_add_susfs_in_gki-android12-5.10.patch ./
          cp ../susfs4ksu/kernel_patches/fs/* ./fs/
          cp ../susfs4ksu/kernel_patches/include/linux/* ./include/linux/
          patch -p1 < 50_add_susfs_in_gki-android12-5.10.patch || true
          
      - name: Apply lz4kd Patches (条件执行)
        if: ${{ inputs.enable_feature_y }}
        run: |
          cd kernel_workspace/kernel_platform
          echo "应用lz4kd补丁..."
          # 这里添加实际的lz4kd补丁应用命令
          
      - name: Generate initial config
        run: |
          cd kernel_workspace/kernel_platform
          make ARCH=arm64 gki_defconfig
          
      - name: Configure Kernel Options
        run: |
          cd kernel_workspace/kernel_platform
          sed -i "s/CONFIG_LOCALVERSION=.*/CONFIG_LOCALVERSION=\"${{ inputs.KERNEL_SUFFIX }}\"/" .config
          
          if [ "${{ inputs.enable_feature_x }}" = "true" ]; then
            ./scripts/config --enable CONFIG_KPM
            echo "已启用KPM功能"
          fi
          
          ./scripts/config --enable CONFIG_TCP_CONG_BBR
          ./scripts/config --set-str CONFIG_DEFAULT_TCP_CONG "bbr"
          
          make ARCH=arm64 olddefconfig
          
      - name: Build Kernel
        run: |
          cd kernel_workspace/kernel_platform
          export KBUILD_BUILD_TIMESTAMP="${{ inputs.KERNEL_TIME }}"
          
          # --- 关键修改：改为下载 tar.gz 包并解压 ---
          echo "正在下载 Clang 工具链..."
          wget https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/main/clang-r547379.tar.gz -O clang-r547379.tar.gz
          echo "正在解压 Clang 工具链..."
          tar -xf clang-r547379.tar.gz
          # 根据解压后的实际目录结构设置 CLANG_PATH
          # 假设解压后会在当前目录生成一个名为 'clang-r547379' 的文件夹
          export CLANG_PATH=$(pwd)/clang-r547379/bin 
          export PATH=${CLANG_PATH}:${PATH}
          echo "Clang 工具链路径已设置为: ${CLANG_PATH}"
          # --- 修改结束 ---
          
          # 开始构建
          make -j$(nproc) ARCH=arm64 CC=clang \
            CROSS_COMPILE=aarch64-linux-gnu- \
            LD=ld.lld \
            NM=llvm-nm
            
      - name: Package Kernel
        run: |
          cd kernel_workspace/kernel_platform
          git clone https://github.com/Kernel-SU/AnyKernel3.git
          cp arch/arm64/boot/Image.gz AnyKernel3/
          
          echo "构建参数:" > AnyKernel3/build-info.txt
          echo "KERNEL_SUFFIX: ${{ inputs.KERNEL_SUFFIX }}" >> AnyKernel3/build-info.txt
          echo "KERNEL_TIME: ${{ inputs.KERNEL_TIME }}" >> AnyKernel3/build-info.txt
          echo "启用KPM: ${{ inputs.enable_feature_x }}" >> AnyKernel3/build-info.txt
          echo "启用lz4kd: ${{ inputs.enable_feature_y }}" >> AnyKernel3/build-info.txt
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Android12-GKI-Kernel
          path: kernel_workspace/kernel_platform/AnyKernel3/*
